### ISSUE TITLE
[REQUEST] Add line/comment with "credit" to generator

### ISSUE THREAD

**Issue by OrdinatorStouff** [TheRandomLabs/ChangelogGenerator#1]
I would like to keep using this tool for All The Mods  pack changelog augmentation, but I also feel it's important to credit you and your tool. I can just copy/paste [a line](https://github.com/AllTheMods/ATM-3/blob/master/changelogs_detail/changelog_atm3_5.7_full.txt#L2) in every time but I thought I'd ask if that's something you might want to put in by default, something even as simple as: `Generated using https://github.com/TheRandomLabs/ChangelogGenerator` perhaps?

Either way, thank you for this tool, I think it really is pretty great.

**Comment by TheRandomLabs** [comment]
Done.
