### ISSUE TITLE
[Request] Modpack Changelog Generator

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/ChangelogGenerator#10]
Hey! Would you consider making a utility tool similar to ChangelogGenerator, that combines and/or compares changelogs from modpacks? A user of mine asked for a smarter way to view all the changelogs from any version to the latest, and I thought that might be up your alley to make :)

**Comment by TheRandomLabs** [comment]
Can I have more details? How would changelogs be combined? What if a mod
was added then removed again, for example?

**Comment by NielsPilgaard** [comment]
I was thinking It would just put together the changelogs of the modpack updates, not the mods themselves.
Example, the URLs combined:
https://minecraft.curseforge.com/projects/enigmatica2expert/files/2577946
https://minecraft.curseforge.com/projects/enigmatica2expert/files/2578639

would equal:
https://gist.github.com/NillerMedDild/bcd2f76446d776157458abf8bb560ee9

**Comment by TheRandomLabs** [comment]
So you mean a GUI where you can select a modpack project, then select two
files? That wouldn't take too long to make.

**Comment by NielsPilgaard** [comment]
Pretty much! However if the two files had updates between them, they should have their challenges added swell.
So running the software on version 1.25 and 1.28 would result in a file with the changelogs from version 1.25, 1.26, 1.27 and 1.28.

**Comment by TheRandomLabs** [comment]
Since the issue on the Enigmatica repository is asking for just a text file, I'll add the functionality to ChangelogGenerator. Since I was going to make a Curse GUI anyway, I'll add changelogs to it as well.

**Comment by NielsPilgaard** [comment]
Sounds great, thank you!

**Comment by TheRandomLabs** [comment]
With ChangelogGenerator 1.10, you can use `java -jar ChangelogGenerator.jar enigmatica2expert` (or any other slug/project ID) and it will generate a changelog history.

**Comment by NielsPilgaard** [comment]
It works perfectly :)
