### ISSUE TITLE
crash on forge version

### ISSUE THREAD

**Issue by Yoosk** [TheRandomLabs/ChangelogGenerator#11]
latest version of generator
[crashlog](https://gist.github.com/7bca035e3809959c2419b472da4a52f7)
between those [1](https://dl.dropboxusercontent.com/s/alxiu896jjv2ua4/manifest.json) and [2](https://dl.dropboxusercontent.com/s/8dw3d0ze290jvdq/old.json)

**Comment by TheRandomLabs** [comment]
Looks like [Forge's changelog](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2759/forge-1.12.2-14.23.4.2759-changelog.txt) is screwed up again. I'll have to implement a workaround for when this happens. I'll release at least a temporary fix tomorrow.

**Comment by TheRandomLabs** [comment]
I released a temporary fix in 1.10.2.

**Comment by Yoosk** [comment]
works perfect, ty.

**Comment by scalda** [comment]
Hi i have been trying to use the 1.10.2 version and i keep getting a forge unknown error?

**Comment by TheRandomLabs** [comment]
Try 1.10.1 for now. I'll look at it soon.

**Comment by TheRandomLabs** [comment]
Looks like Forge's changelogs are still broken. I'll have to redo the code for retrieving Forge changelogs.

**Comment by scalda** [comment]
Is there any way to tell the generator to ignore forge for the time being?

**Comment by TheRandomLabs** [comment]
No, sorry, but I'll add a temporary fix tomorrow. I'll implement a more
permanent fix on the weekend.

**Comment by scalda** [comment]
ok thank you

**Comment by Yoosk** [comment]
`Bump` as forge 2765 breaks it again.

**Comment by TheRandomLabs** [comment]
Damn, I thought I'd at least fixed the crash. It looks like they pretty much reset the changelog, so I'll have to download two changelogs now.

**Comment by TheRandomLabs** [comment]
A slightly less temporary fix should be included in 1.11. I'll write a more permanent fix after I'm done rewriting a few other projects.

**Comment by TheRandomLabs** [comment]
I'll start working on this and related projects again now that I've released RandomPortals.
