### ISSUE TITLE
API Cannot Fetch Latest forge build

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [TheRandomLabs/ChangelogGenerator#12]
Using the Changelog Generator by you guys, and it spits this error

com.therandomlabs.curseapi.minecraft.forge.InvalidForgeVersionException: Invalid Forge version: 1.12.2-14.23.4.2766

Im assumbing the bot stoped working because its not picking up a thing

**Comment by CrankySupertoonArchive** [comment]
https://github.com/TheRandomLabs/CurseAPI-Minecraft/issues/1

**Comment by TheRandomLabs** [comment]
Closing this in favor of https://github.com/TheRandomLabs/CurseAPI-Minecraft/issues/1.
