### ISSUE TITLE
This is nothing i should be proud of but an automatic User Interface for the compiler.

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [TheRandomLabs/ChangelogGenerator#14]
Using some simple Batch File Language i created a bat script to make the Changelog works with less inputs.

Running the bat file with these 4 lines

@echo off
set /p ch1="Old Manifest: "
set /p ch2="New Manifest: "
java -jar ChangelogGenerator.jar %ch1% %ch2%

pretty much what you do is put your 2 manifest in the directory of the jar and batch file. Then running the bat will ask for the old manifest file aka your old version, You can type your version or tab it, and then the new manifest. Then the batch script will use your inputs as variables and automatically compile it. Then copy your Shortchangelog file or the normal changelog to curseforge

**Comment by TheRandomLabs** [comment]
You can use this if you want. Eventually, I'll improve the command-line interface and maybe write a GUI.
