### ISSUE TITLE
No changelog is generated - Program abruptly ends?

### ISSUE THREAD

**Issue by Norway174** [TheRandomLabs/ChangelogGenerator#15]
So I was testing the program out on two different manifest JSONs. Of the same modpack. But from the different versions.

It seems to download all the file data just fine.

And then there's a couple of errors for some mods when it tries to download the changelog data.
But it still seems to keep going. Except for when it reaches ActuallyAdditions.

Here's the full CMD log: [TXEsgW6B](https://pastebin.com/TXEsgW6B)

I've also attached with both the manifest's and the bat file I've used to run this, in the .zip file.
[generateLog.zip](https://github.com/TheRandomLabs/ChangelogGenerator/files/2774861/generateLog.zip)

I even tried running it as admin. And still wouldn't generate any files. Just stops with the same error.

So I'm guessing it might be caused by ActuallyEdditions?
But why would it stop at that error, and not the others? 

**Edit:**
Forgot to mention. I'm on the latest release. I just downloaded it today.
On 1.12.4.

**Comment by TheRandomLabs** [comment]
The other errors are normal. ChangelogGenerator is trying to download the changelogs for archived files, but it tries multiple times to make sure they actually are archived and not temporarily inaccessible.

**Comment by TheRandomLabs** [comment]
This is fixed in 1.13.
