### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/ChangelogGenerator#19]
Hey o/ I was wondering if you would allow me to include the ChangelogGenerator jar in my [ModpackUploader project](https://github.com/NillerMedDild/ModpackUploader)? 

It's an automation tool for modpack makers, and automated mod changelogs would be cool to add to it.

My project is also under the MIT license, if that makes a difference.

**Comment by TheRandomLabs** [comment]
Sure, go ahead, although I would recommend downloading the latest jar at
runtime.

**Comment by NielsPilgaard** [comment]
Thanks, and that's a good idea :)
