### ISSUE TITLE
How does one use this program?

### ISSUE THREAD

**Issue by katubug** [TheRandomLabs/ChangelogGenerator#20]
Pardon my extremely rudimentary question but, how do you use this? I attempted to just execute the jar (both from my initial download directory and from my MC mods directory), but that didn't seem to have any effect. Having it in the `/mods/` folder and starting up the game doesn't seem to have generated any files that I could see in `mods`, `config`, `logs`, or the primary minecraft directory.

I did check the readme a few times but either I'm missing something simple (which is extremely possible), or it doesn't explicitly say. In any case, I am out of ideas, haha. Thank you very much for your time!

**Comment by NielsPilgaard** [comment]
You can use it by running the following command in a command prompt `java -jar ChangelogGenerator.jar oldmanifest.json manifest.json` where oldmanifest.json is the manifest file from the older version modpack, and manifest.json is the manifest file from the newer version modpack.

The manifest can be found inside a modpack's CurseForge zipfile, downloadable directly from CurseForge.

I hope that helps :)

**Comment by katubug** [comment]
Thank you very much! I appreciate you taking the time to explain to me. And thank you also for the great tool! I'm looking forward to not having to copy everything manually, haha!

**Comment by TheRandomLabs** [comment]
Thanks, you did my job for me! :)

**Comment by kreezxil** [comment]
@TheRandomLabs part of your job. You still need to update the README.md to show how to use this.

**Comment by TheRandomLabs** [comment]
Haha, I was going to do that when I finally added proper command-line handling, but school got in the way. 😛
