### ISSUE TITLE
Changelog Generator not working

### ISSUE THREAD

**Issue by Wxrlds** [TheRandomLabs/ChangelogGenerator#22]
Script in bat file:
```
java -jar ChangelogGenerator.jar Technocratica
Pause
```
when doing this, it generates the following error for me:
https://gist.github.com/Wxrlds/34267376c951c31c34843fc5f48e8868
Edit changed link because the old one seems broken

**Comment by NielsPilgaard** [comment]
Looks like the old CurseForge url has been fully deprecated. The Changelog Generator should be redirected to the new URL, which for Technocratica would be `https://www.curseforge.com/minecraft/modpacks/technocratica`

**Comment by TheRandomLabs** [comment]
Looks like CloudFlare doesn't like ChangelogGenerator. I'll have to find a way to bypass it.

**Comment by TheRandomLabs** [comment]
This is the same issue as MultiMC/MultiMC5#2859.

**Comment by NielsPilgaard** [comment]
Any progress on this issue? :)

**Comment by TheRandomLabs** [comment]
No, I haven't yet investigated any ways to bypass this. We'll find out soon!

2019년 10월 17일 (목) 21:32, Niels Pilgaard Grøndahl <notifications@github.com>님이
작성:

**Comment by katubug** [comment]
Just wanted to say thank you for your hard work! Looking forward to a fix :)

**Comment by TheRandomLabs** [comment]
Thanks! Sorry that I haven't been able to work on this recently. I have
exams coming up as well, so it might be a bit longer than expected.

**Comment by NielsPilgaard** [comment]
No worries :)

**Comment by katubug** [comment]
No problem! Good luck with your exams! You're gonna kill it :D

**Comment by Wxrlds** [comment]
It has been a while, are there any updates?

**Comment by TheRandomLabs** [comment]
Yes, I've rewritten CurseAPI and CurseAPI-Minecraft, and there are only a few more things I have to do before I can rewrite ChangelogGenerator.

**Comment by NielsPilgaard** [comment]
Awesome!! I miss the Changelog Generator a lot.

**Comment by TheRandomLabs** [comment]
A WIP build can be downloaded [here](https://jitci.com/gh/TheRandomLabs/ChangelogGenerator/builds/b1DWPKS7CB3M0817MPVSHE1JEQ/ChangelogGenerator-2.0.0.jar). I'm closing this issue as there's *technically* a working build now. :)

**Comment by NielsPilgaard** [comment]
That link shows a white page with the word Unauthorized on it :P

**Comment by TheRandomLabs** [comment]
Whoops, [this should be better](https://github.com/TheRandomLabs/ChangelogGenerator/releases/tag/v2.0.0-pre).
