### ISSUE TITLE
Changelog Generator not working

### ISSUE THREAD

**Issue by Wxrlds** [TheRandomLabs/ChangelogGenerator#23]
Title says it all.
Script in bat file:
```
java -jar ChangelogGenerator-2.0.0-pre.jar Technocratica
Pause
```
Error: https://gist.github.com/Wxrlds/cdcf5a4a25923744e7d9188fe63130ca

**Comment by NielsPilgaard** [comment]
To quote the 2.0.0 pre-release:
> A prerelease for ChangelogGenerator 2.0.0. All functionality is not yet implemented, and there are no command-line options. It reads old.json for the old manifest and new.json for the new manifest.

**Comment by Wxrlds** [comment]
It doesn't matter if I use the bat file or not but when I use the bat file I can look at errors.
Also I think it might be because a file was deleted from Curseforge :)

**Comment by TheRandomLabs** [comment]
Thanks for reporting this! You are correct in that it is because a file was deleted.
