### ISSUE TITLE
Error Duplicate Key

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/ChangelogGenerator#28]
Hey o/ 

sing 2.0.0-pre2 on Enigmatica 4 between versions 0.4.9 and 0.4.10 results in an exception:

https://gist.github.com/NillerMedDild/cd2f478c4887e17c7e2e5b93ca49a7e4

**Comment by TheRandomLabs** [comment]
This is occurring beceause the project ID `289712` (Tetra) is defined twice in the old manifest. This is fixed in 2.0.0-pre3. :)

**Comment by NielsPilgaard** [comment]
Awesome, thanks :) It's great to have the Changelog Generator back in action!
