### ISSUE TITLE
Changlelogs are blank/empty

### ISSUE THREAD

**Issue by OrdinatorStouff** [TheRandomLabs/ChangelogGenerator#3]
Using release from Jan 19th

Trying to generate log from ATM3 5.7 to 5.8 and the program closes but with the changelog full and short both completely empty.

I have the command window output as well as both old and new jsons I am using if it helps: 

[changelog.zip](https://github.com/TheRandomLabs/ChangelogGenerator/files/1760227/changelog.zip)

**Comment by Thrandor** [comment]
I am having the same issue using version 1.3 trying to generate a changelog for FTB Revelations 1.5 to 1.6.  I attempted using older versions of the generator but it ended up with the same result of both the full and short changelog generating empty.

I attached everything I used but the jar file.

[changelog generator.zip](https://github.com/TheRandomLabs/ChangelogGenerator/files/1760991/changelog.generator.zip)

**Comment by TheRandomLabs** [comment]
Try 1.3.1. CurseForge's widget API has been a bit weird lately.

**Comment by Thrandor** [comment]
Version 1.3.1 worked for me.  Thank you!

**Comment by OrdinatorStouff** [comment]
Same here, 1.3.1 working as intended again, thanks~
