### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by kreezxil** [TheRandomLabs/ChangelogGenerator#34]
Thank you for responding to #33, what I'm seeing is very impressive https://gist.github.com/kreezxil/b6c1ecaaa64564bd582a889187559b20
I'd like to see either a config or command-line arguments to limit how much of a mod's changelog is pulled in as lines for example `-l 5` which would mean pull in 5 lines. 
A toggle for mod links would be nice too, for example `--modLinks` if it exists the source URL to the mod is listed below the mod name or on the level with it.

Granted by itself it's awesome and I'm feeling compelled to send you some kind of incentive. Do you have a Patreon?

**Comment by TheRandomLabs** [comment]
I would love to implement options for manipulating formatting, and your ideas are great.
I'd never considered opening a Patreon, but I'll see if I can start one! I greatly appreciate your offer for support. 😄 
**EDIT:** [Done](https://www.patreon.com/therandomlabs).

**Comment by kreezxil** [comment]
is there a projected time frame for the implementation of the options?

**Comment by TheRandomLabs** [comment]
I'll see if I can get to it this week. 😛

**Comment by kreezxil** [comment]
That'd be great.

**Comment by TheRandomLabs** [comment]
I haven't added the maximum entry line count yet (I'll do this tomorrow), but I've added an option to generate Markdown output, which includes the mod links you requested.

**Comment by kreezxil** [comment]
nice, you got a Patreon or something similar up yet?

**Comment by NielsPilgaard** [comment]
He did: https://www.patreon.com/therandomlabs😄 
Edit: I tried out the --markdown toggle and it looks great, thanks for that.

**Comment by TheRandomLabs** [comment]
😄

**Comment by TheRandomLabs** [comment]
I've implemented `--lines`. 🥳

**Comment by kreezxil** [comment]
nice
