### ISSUE TITLE
2.0.0-pre7

### ISSUE THREAD

**Issue by kreezxil** [TheRandomLabs/ChangelogGenerator#35]
Ok, coming along nicely. Not sure where this fits in. In the attached files Bewitchment comes up way too much, although for each it is doing only 5 lines like I set it too.

| json | gist link |
| -- | -- |
| new.json | https://gist.github.com/0bcae2ac7a0b2c65f87f3328de9172ab |
| old.json | https://gist.github.com/cf6c8bf0347f8fb1f9d2911d7f975a71 |

[Changelog.md](https://gist.github.com/8a67c9afbffc4524722e7f74090ecaac)

The actual command line:
`java -jar ChangelogGenerator-2.0.0-pre7.jar --lines=5 -o=Svet+Draku-1.1.2/manifest.json -n=Svet\ Draku-1.2.3/manifest.json -m`

**Comment by TheRandomLabs** [comment]
Would you want an option to specify the maximum number of entries?

**Comment by TheRandomLabs** [comment]
I'm about to release a build with `--entries`.

**Comment by kreezxil** [comment]
what does --entries do? is that for when a changelog lists multiple
versions of itself? like as in bewitchment?

**Comment by TheRandomLabs** [comment]
Yep.

**Comment by kreezxil** [comment]
I would make that option default to 1, or w/e the bareminum value is. and
the --lines entry should default to 5. That way if they're not specified
it's still a very useful tool for creating changelogs that users will read
on CF. or elsewhere.

**Comment by TheRandomLabs** [comment]
Nice idea, I'll set them both to 5 by default.

**Comment by kreezxil** [comment]
i don't see a need to see multiple entries between mod diffs, 1 would be a
better default for entries.

What you could add is a config file that if present, and the command arg
option not used will set the value. ie the config sets default values.

**Comment by TheRandomLabs** [comment]
I personally believe it can be useful for a few entries to be displayed, so I'm not keen on changing it to 1. Would there be any advantage to having a configuration file rather than having a shell script pass command-line options?

**Comment by kreezxil** [comment]
probably not

found a great linux program called fuse-zip that mounts archives, just
occurred to me, that while your program doesn't need to mount them, why not
just specify the old and the new archives and it pulls what it needs from
both.

**Comment by TheRandomLabs** [comment]
I can definitely do that.

**Comment by kreezxil** [comment]
sweet

**Comment by TheRandomLabs** [comment]
Done!
