### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/ChangelogGenerator#4]
Hey! 

I'm getting this error when using the script to check between update 1.18 and 1.19 of Enigmatica 2: Expert:

https://gist.github.com/NillerMedDild/6198b74773ee0b7764c95f4d003abe89

Thanks for this great tool, it has made my life a lot easier :)

**Comment by TheRandomLabs** [comment]
Thanks for reporting this.

**Comment by TheRandomLabs** [comment]
Something I did within the last month seems to have fixed this issue, so I'll patch some things up and release.

**Comment by NielsPilgaard** [comment]
Thanks!

**Comment by TheRandomLabs** [comment]
Done, and you can find changelog.txt and shortchangelog.txt in this repo, since I used your manifests as a test. 😄

**Comment by NielsPilgaard** [comment]
Haha, thank you :D
