### ISSUE TITLE
Crash when download mods that were deleted from curse

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [TheRandomLabs/ChangelogGenerator#6]
When i ran it it split out a missing Id error. I googled the id and found that its a deleted mod from curse. Can you fix. I know it might be hard. Temporary fix was to delete it from the manifest

**Comment by TheRandomLabs** [comment]
Whoops, I thought I already fixed that.

**Comment by TheRandomLabs** [comment]
Tell me if 1.6.4 works, and if it doesn't, send me the full log.

**Comment by TheRandomLabs** [comment]
Never mind, I've figured it out.
