### ISSUE TITLE
Error When Reading From Addons

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/ChangelogGenerator#7]
Hey o/

I have a new bug for you:
https://gist.github.com/NillerMedDild/48b575943e27cbbf9b8901211185724f

Just fyi, I removed 7 mods between the updates it's generating a log for, I thought that might help.

**Comment by TheRandomLabs** [comment]
Looks like CurseMeta's down right now. I'll add a command-line option to retrieve data by parsing CurseForge's HTML instead, although it'll be slightly slower.

**Comment by TheRandomLabs** [comment]
Well, that took a lot longer than expected, but it's fixed in 1.9 now. Use "avoidCurseMeta" as the third command line argument for now.

**Comment by NielsPilgaard** [comment]
Alright, thanks for the swift fix as always :D

**Comment by TheRandomLabs** [comment]
No problem.
