### ISSUE TITLE
crash on forge version

### ISSUE THREAD

**Issue by Yoosk** [TheRandomLabs/ChangelogGenerator#8]
Doesn't generate change logs when it encounters some issue with forge version.
[log](https://gist.github.com/fad0a9067892adec8d008f4bf60a8f99)
Was comparing jsons from those 2 packs:
[atm3 5.9.1](https://minecraft.curseforge.com/projects/all-the-mods-3/files/2543756) and [atm3 5.9.2](https://minecraft.curseforge.com/projects/all-the-mods-3/files/2547585)

**Comment by TheRandomLabs** [comment]
It looks like the latest version of Forge [doesn't have a changelog](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2708/forge-1.12.2-14.23.4.2708-changelog.txt). I'll release a hotfix.
